### ISSUE TITLE
Looking for Mouse annotation file

### ISSUE THREAD

**Issue by Garlapav** [Hoffmann-Lab/TEdetectionEvaluation#11]
Hie, 

Thanks for the excellent paper comparing the all tools for TE expression. I have one small question. Do you have mouse annotation file for Telescope..? I am not able to find one.

Best,

Venkat

**Comment by roschwarz** [comment]
Solved via email. An annotation is available on [zenodo.org ](https://zenodo./record/4561751)[https://zenodo./record/4561751](https://zenodo.org/record/4561751).
