### ISSUE TITLE
 Consult for align_parset.py

### ISSUE THREAD

**Issue by dtx282000** [Hoffmann-Lab/TEdetectionEvaluation#8]
Dear, Dr. Robert Schwarz,

I am new one for the TE analysis. Through looking your paper, I found the script of align_parset.py is very important for converting the align file to bed or gtf file.

But, when I run the script, some error is always existed in my iTerm2.  The error is as follows:

Dear, Dr. Robert Schwarz,

I am new one for the TE analysis. Through looking your paper, I found the script of align_parset.py is very important for converting the align file to bed or gtf file. But, when I run the script, some error is always existed in my iTerm2.  The error is as follows:

![image](https://user-images.githubusercontent.com/24269804/148038250-b3fef632-3436-4039-bdce-4eb695e65d4c.png)

Also, the command line “pip install pylibs” is also not solved my error. Now, I haven’t deal with this error. Please help me to solve this error.

Best regards

**Comment by roschwarz** [comment]
Hi dtx282000,

sorry, I forgot to upload my personal library. I have done it now, you need to pull the latest "version" and it should work. If not, please let me know.

Best,
Robert

**Comment by dtx282000** [comment]
Dear, Dr. Robert Schwarz,


This script is ok. But I found another script existed one error, which is as follows:



Please told me how to deal with it. Thanks!


Best,

Deng

**Comment by roschwarz** [comment]
Hi Deng,

you forgot to name the script with the other error. Please give me the name of the script and error that occurred.

Best,
Robert

**Comment by dtx282000** [comment]
Dear Dr. Robert Schwarz,

The name of script is generateDic.py. The error is as follows:


 

Best

Deng

**Comment by roschwarz** [comment]
I'm assuming that you added an image with the error message, however, I can't see it. Maybe you can just copy the error message.

Best,
Robert

**Comment by dtx282000** [comment]
Traceback (most recent call last):
  File "./generateDict.py", line 87, in <module>
    main()
  File "./generateDict.py", line 73, in main
    files = {'squire': sys.argv[1], 'myAnno': sys.argv[2]}
IndexError: list index out of range

**Comment by roschwarz** [comment]
You need to add the bed files as arguments to the script call

`python generateDict.py <.bed-file from squire> <.bed-file from the align_parser.py output>`

SQuIRE creates a squire_clean directory where the .bed-file from squire is contained and the second bed file is generated by
the script that you named in the top post (align_parser.py).

Best,
Robert

**Comment by dtx282000** [comment]
Thank you for your help. I will try it.

Best,

Deng
